# Generated by Django 4.1.6 on 2023-02-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Product',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
